### ISSUE TITLE
无法联系上下文 进行回答 

### ISSUE THREAD

**Issue by louisqin** [zccbbg/chatgpt-springboot-service#4]
无法联系上下文 进行回答

**Comment by Shangguanliang** [comment]
你解决了吗

**Comment by Shangguanliang** [comment]
> 无法联系上下文 进行回答

我解决了，我的方法是把messages的历史放入chatCompletion里然后再发送给chatgpt
![mywebsocket](https://github.com/zccbbg/chatgpt-springboot-service/assets/61975464/42601e48-12da-4490-8125-d52f9adf6420)

![chatgpt](https://github.com/zccbbg/chatgpt-springboot-service/assets/61975464/6bb1112a-273b-4d75-9afb-c9a78776dca2)
